### ISSUE TITLE
Ideas on possible improvements

### ISSUE THREAD

**Issue by maciejsaw** [garsidestephen/qnaclient#1]
Thanks for this code because it helped me to see how you make request to Microsoft endpoint with jQuery :)

Here are some ideas how to improve this
- Provide this only as a JS script so that it can be plugged in to a website via CDN, for example RawGit. You can store Html template and CSS inside JS as well.
- Add option to render this in a specific element on a website, so that it can be a part of a bigger website
- Separate the API part from CSS and HTML so that we can use the parsing code but render the answers, dates etc. inside any element - this will allow better customization of the look
- Make an online demo
- Add a gif image that shows how this looks
- Use library to parse markdown, ex. https://github.com/showdownjs/showdown

**Comment by garsidestephen** [comment]
Thanks for the feedback :) - 

- You can see an online demo at www.stephengarside.co.uk (just click on the chat icon bottom left).  
- There is an option to inject the window into either a class or id (use parameter **pageContainerId** or **pageContainerClass**).

- Take your point on bundling it into 1 js call - will take a look + added an image to show how the window renders.

I am also in the process of adding support for 'chips' in the response + the ability to run it in 2 modes - either a chat window or as part of a document i.e. interactive blog article.

Thanks again for the feedback - much appreciated.
